// SPDX-License-Identifier: Apache-2.0
//! Inner Thoughts Engine — Proactive AI Suggestions + Cascade Inference
//!
//! Based on arXiv:2501.00383 "Proactive Conversational Agents with Inner Thoughts"
//! (CHI 2025, 82% user preference over non-proactive agents).
//!
//! **5-stage pipeline:**
//! 1. Trigger  — user activity, context change, pattern, error, time-based
//! 2. Retrieval — pull relevant memories from ForgeMemory
//! 3. Thought Formation — generate internal hypotheses via Ollama
//! 4. Evaluation — score by relevance × urgency × novelty × confidence
//! 5. Participation — surface suggestion only if score ≥ threshold AND user idle
//!
//! **Cascade Inference:**
//! Try Ollama (local, free) first. If model self-reports confidence < 0.8,
//! escalate to OpenRouter free-tier cloud model. Saves cost, preserves privacy.
//!
//! All thoughts persisted to `~/.impforge/thoughts/` as JSON files.

use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};

use chrono::Utc;
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::error::{AppResult, ImpForgeError};

// ─────────────────────────────────────────────────────────────────────────────
// Data Types
// ─────────────────────────────────────────────────────────────────────────────

/// What triggered the AI to form a thought.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum TriggerType {
    /// User opened a file, switched module, or performed an action.
    UserActivity,
    /// New data available, service status changed.
    ContextChange,
    /// Scheduled check (e.g. "meeting in 15 min").
    TimeBasedReminder,
    /// AI noticed a pattern in user behavior.
    PatternDetected,
    /// Something went wrong in a background process.
    ErrorDetected,
    /// Team goal update or progress milestone.
    GoalProgress,
}

/// Priority level for surfacing suggestions.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum SuggestionPriority {
    Low,
    Medium,
    High,
    Critical,
}

/// An internal thought generated by the engine.
/// Thoughts are private — only surfaced as `Suggestion` when score is high enough.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Thought {
    pub id: String,
    pub content: String,
    pub trigger: TriggerType,
    /// How relevant is this to the user's current activity (0.0–1.0).
    pub relevance: f32,
    /// How time-sensitive is this (0.0–1.0).
    pub urgency: f32,
    /// How new or surprising is this information (0.0–1.0).
    pub novelty: f32,
    /// How confident is the AI in this thought (0.0–1.0).
    pub confidence: f32,
    /// Combined score: relevance×0.3 + urgency×0.3 + novelty×0.2 + confidence×0.2.
    pub score: f32,
    pub created_at: String,
    /// Whether this thought was surfaced to the user.
    pub surfaced: bool,
    /// Whether the user dismissed it (negative feedback).
    pub dismissed: bool,
}

/// A user-visible suggestion derived from a scored thought.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Suggestion {
    pub id: String,
    pub thought_id: String,
    pub title: String,
    pub description: String,
    /// CTA button text (e.g. "Open", "Apply", "Fix").
    pub action_label: Option<String>,
    /// Route to navigate to when accepted (e.g. "/chat", "/ide").
    pub action_route: Option<String>,
    pub priority: SuggestionPriority,
    pub created_at: String,
}

/// Tracks what the user is currently doing so the engine knows when to interrupt.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserState {
    pub current_module: String,
    pub is_typing: bool,
    pub last_action_at: String,
    pub idle_seconds: u64,
    /// True if idle > threshold seconds — safe to show a suggestion.
    pub interruptible: bool,
}

impl Default for UserState {
    fn default() -> Self {
        Self {
            current_module: "home".to_string(),
            is_typing: false,
            last_action_at: Utc::now().to_rfc3339(),
            idle_seconds: 0,
            interruptible: true,
        }
    }
}

/// Configuration for the thoughts engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThoughtsConfig {
    pub enabled: bool,
    /// Minimum combined score to surface a thought as a suggestion (0.0–1.0).
    pub min_score_to_surface: f32,
    /// Maximum suggestions queued at once.
    pub max_suggestions: u32,
    /// How often the engine checks for new thoughts (seconds).
    pub check_interval_seconds: u32,
    /// User must be idle this long before showing a suggestion.
    pub idle_threshold_seconds: u32,
}

impl Default for ThoughtsConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            min_score_to_surface: 0.6,
            max_suggestions: 3,
            check_interval_seconds: 30,
            idle_threshold_seconds: 5,
        }
    }
}

/// Result of a cascade inference call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CascadeResult {
    pub response: String,
    pub model_used: String,
    pub confidence: f32,
    /// Whether the request was escalated from local to cloud.
    pub escalated: bool,
    pub latency_ms: u64,
}

/// Aggregate statistics for cascade inference.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CascadeStats {
    pub total_inferences: u64,
    pub local_inferences: u64,
    pub cloud_inferences: u64,
    pub avg_local_confidence: f32,
    pub avg_latency_ms: f64,
    /// Estimated cloud API cost saved by using local models first.
    pub estimated_cost_saved_usd: f64,
}

// ─────────────────────────────────────────────────────────────────────────────
// Engine State (managed by Tauri)
// ─────────────────────────────────────────────────────────────────────────────

/// The in-memory engine that Tauri manages via `app.manage()`.
pub struct InnerThoughtsEngine {
    pub thoughts: RwLock<Vec<Thought>>,
    pub suggestions: RwLock<Vec<Suggestion>>,
    pub user_state: RwLock<UserState>,
    pub config: RwLock<ThoughtsConfig>,
    // Cascade stats (atomic for lock-free counting)
    total_inferences: AtomicU64,
    local_inferences: AtomicU64,
    cloud_inferences: AtomicU64,
    total_local_confidence: RwLock<f64>,
    total_latency_ms: RwLock<f64>,
}

impl InnerThoughtsEngine {
    pub fn new() -> Self {
        let config = load_config_from_disk().unwrap_or_default();
        Self {
            thoughts: RwLock::new(Vec::new()),
            suggestions: RwLock::new(Vec::new()),
            user_state: RwLock::new(UserState::default()),
            config: RwLock::new(config),
            total_inferences: AtomicU64::new(0),
            local_inferences: AtomicU64::new(0),
            cloud_inferences: AtomicU64::new(0),
            total_local_confidence: RwLock::new(0.0),
            total_latency_ms: RwLock::new(0.0),
        }
    }

    /// Record a completed inference for statistics.
    fn record_inference(&self, local: bool, confidence: f32, latency_ms: u64) {
        self.total_inferences.fetch_add(1, Ordering::Relaxed);
        if local {
            self.local_inferences.fetch_add(1, Ordering::Relaxed);
            *self.total_local_confidence.write() += confidence as f64;
        } else {
            self.cloud_inferences.fetch_add(1, Ordering::Relaxed);
        }
        *self.total_latency_ms.write() += latency_ms as f64;
    }

    fn get_stats(&self) -> CascadeStats {
        let total = self.total_inferences.load(Ordering::Relaxed);
        let local = self.local_inferences.load(Ordering::Relaxed);
        let cloud = self.cloud_inferences.load(Ordering::Relaxed);
        let total_conf = *self.total_local_confidence.read();
        let total_lat = *self.total_latency_ms.read();

        let avg_local_conf = if local > 0 {
            (total_conf / local as f64) as f32
        } else {
            0.0
        };
        let avg_lat = if total > 0 {
            total_lat / total as f64
        } else {
            0.0
        };
        // Rough estimate: each cloud call ≈ $0.001 (free-tier models are $0)
        // but we count the "would have cost" at typical GPT-4o-mini rate
        let saved = local as f64 * 0.0005;

        CascadeStats {
            total_inferences: total,
            local_inferences: local,
            cloud_inferences: cloud,
            avg_local_confidence: avg_local_conf,
            avg_latency_ms: avg_lat,
            estimated_cost_saved_usd: saved,
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Persistence (JSON files in ~/.impforge/thoughts/)
// ─────────────────────────────────────────────────────────────────────────────

/// Resolve the thoughts storage directory, creating it if needed.
fn thoughts_dir() -> Result<PathBuf, ImpForgeError> {
    let home = dirs::home_dir().ok_or_else(|| {
        ImpForgeError::filesystem("HOME_DIR_NOT_FOUND", "Cannot determine home directory")
    })?;
    let dir = home.join(".impforge").join("thoughts");
    if !dir.exists() {
        std::fs::create_dir_all(&dir).map_err(|e| {
            ImpForgeError::filesystem("THOUGHTS_DIR_CREATE_FAILED", e.to_string())
        })?;
    }
    Ok(dir)
}

/// Config file path.
fn config_path() -> Result<PathBuf, ImpForgeError> {
    let home = dirs::home_dir().ok_or_else(|| {
        ImpForgeError::filesystem("HOME_DIR_NOT_FOUND", "Cannot determine home directory")
    })?;
    let dir = home.join(".impforge");
    if !dir.exists() {
        std::fs::create_dir_all(&dir).map_err(|e| {
            ImpForgeError::filesystem("CONFIG_DIR_CREATE_FAILED", e.to_string())
        })?;
    }
    Ok(dir.join("thoughts_config.json"))
}

fn load_config_from_disk() -> Result<ThoughtsConfig, ImpForgeError> {
    let path = config_path()?;
    if !path.exists() {
        return Ok(ThoughtsConfig::default());
    }
    let data = std::fs::read_to_string(&path)?;
    serde_json::from_str(&data).map_err(|e| {
        ImpForgeError::config("CONFIG_PARSE_FAILED", format!("Failed to parse thoughts config: {e}"))
    })
}

fn save_config_to_disk(config: &ThoughtsConfig) -> Result<(), ImpForgeError> {
    let path = config_path()?;
    let data = serde_json::to_string_pretty(config).map_err(|e| {
        ImpForgeError::internal("CONFIG_SERIALIZE_FAILED", e.to_string())
    })?;
    std::fs::write(&path, data)?;
    Ok(())
}

/// Persist a thought to disk as a JSON file.
fn persist_thought(thought: &Thought) -> Result<(), ImpForgeError> {
    let dir = thoughts_dir()?;
    let filename = format!("{}.json", thought.id);
    let data = serde_json::to_string_pretty(thought).map_err(|e| {
        ImpForgeError::internal("THOUGHT_SERIALIZE_FAILED", e.to_string())
    })?;
    std::fs::write(dir.join(filename), data)?;
    Ok(())
}

/// Load thought history from disk (most recent first).
fn load_thought_history(limit: u32) -> Result<Vec<Thought>, ImpForgeError> {
    let dir = thoughts_dir()?;
    let mut entries: Vec<(std::time::SystemTime, PathBuf)> = Vec::new();

    let read_dir = std::fs::read_dir(&dir).map_err(|e| {
        ImpForgeError::filesystem("THOUGHTS_DIR_READ_FAILED", e.to_string())
    })?;

    for entry_result in read_dir {
        let entry = match entry_result {
            Ok(e) => e,
            Err(_) => continue,
        };
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let modified = entry
            .metadata()
            .ok()
            .and_then(|m| m.modified().ok())
            .unwrap_or(std::time::SystemTime::UNIX_EPOCH);
        entries.push((modified, path));
    }

    // Sort newest first
    entries.sort_by(|a, b| b.0.cmp(&a.0));
    entries.truncate(limit as usize);

    let mut thoughts = Vec::with_capacity(entries.len());
    for (_, path) in entries {
        let data = match std::fs::read_to_string(&path) {
            Ok(d) => d,
            Err(_) => continue,
        };
        match serde_json::from_str::<Thought>(&data) {
            Ok(t) => thoughts.push(t),
            Err(_) => continue,
        }
    }
    Ok(thoughts)
}

// ─────────────────────────────────────────────────────────────────────────────
// Thought Scoring
// ─────────────────────────────────────────────────────────────────────────────

/// Calculate a combined score from the 4 dimensions.
/// Weights: relevance 30%, urgency 30%, novelty 20%, confidence 20%.
fn calculate_score(relevance: f32, urgency: f32, novelty: f32, confidence: f32) -> f32 {
    let r = relevance.clamp(0.0, 1.0);
    let u = urgency.clamp(0.0, 1.0);
    let n = novelty.clamp(0.0, 1.0);
    let c = confidence.clamp(0.0, 1.0);
    r * 0.3 + u * 0.3 + n * 0.2 + c * 0.2
}

/// Map a combined score to a suggestion priority.
fn score_to_priority(score: f32) -> SuggestionPriority {
    if score >= 0.9 {
        SuggestionPriority::Critical
    } else if score >= 0.75 {
        SuggestionPriority::High
    } else if score >= 0.6 {
        SuggestionPriority::Medium
    } else {
        SuggestionPriority::Low
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Ollama Integration (non-streaming, for background thought generation)
// ─────────────────────────────────────────────────────────────────────────────

/// Schema for the JSON array Ollama should return.
#[derive(Debug, Deserialize)]
struct OllamaThoughtItem {
    content: String,
    #[serde(default)]
    relevance: f32,
    #[serde(default)]
    urgency: f32,
    #[serde(default)]
    novelty: f32,
    #[serde(default)]
    confidence: f32,
    #[serde(default)]
    title: Option<String>,
    #[serde(default)]
    action_label: Option<String>,
    #[serde(default)]
    action_route: Option<String>,
}

/// Ollama /api/chat response (non-streaming).
#[derive(Debug, Deserialize)]
struct OllamaChatResponse {
    #[serde(default)]
    message: Option<OllamaChatMsg>,
}

#[derive(Debug, Deserialize)]
struct OllamaChatMsg {
    #[serde(default)]
    content: String,
}

/// Resolve the Ollama URL from environment or default.
fn resolve_ollama_url() -> String {
    std::env::var("OLLAMA_URL")
        .or_else(|_| std::env::var("OLLAMA_HOST"))
        .unwrap_or_else(|_| "http://localhost:11434".to_string())
        .trim_end_matches('/')
        .to_string()
}

/// Call Ollama chat endpoint (non-streaming) for thought generation.
async fn ollama_generate(
    model: &str,
    system_prompt: &str,
    user_prompt: &str,
) -> Result<String, ImpForgeError> {
    let url = resolve_ollama_url();
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .build()
        .map_err(|e| ImpForgeError::internal("HTTP_CLIENT_ERROR", e.to_string()))?;

    let body = serde_json::json!({
        "model": model,
        "messages": [
            { "role": "system", "content": system_prompt },
            { "role": "user", "content": user_prompt },
        ],
        "stream": false,
        "options": {
            "temperature": 0.7,
            "num_predict": 512,
        }
    });

    let resp = client
        .post(format!("{url}/api/chat"))
        .json(&body)
        .send()
        .await
        .map_err(|e| {
            if e.is_connect() {
                ImpForgeError::service(
                    "OLLAMA_UNREACHABLE",
                    "Cannot connect to Ollama for thought generation",
                )
                .with_suggestion("Start Ollama with: ollama serve")
            } else if e.is_timeout() {
                ImpForgeError::service("OLLAMA_TIMEOUT", "Ollama thought generation timed out")
            } else {
                ImpForgeError::service("OLLAMA_REQUEST_FAILED", e.to_string())
            }
        })?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body_text = resp.text().await.unwrap_or_default();
        return Err(ImpForgeError::service(
            "OLLAMA_HTTP_ERROR",
            format!("Ollama returned HTTP {status}"),
        )
        .with_details(body_text));
    }

    let parsed: OllamaChatResponse = resp.json().await.map_err(|e| {
        ImpForgeError::service("OLLAMA_PARSE_ERROR", format!("Failed to parse Ollama response: {e}"))
    })?;

    Ok(parsed
        .message
        .map(|m| m.content)
        .unwrap_or_default())
}

/// Extract a self-reported confidence score from an Ollama response.
/// Asks the model to rate its own confidence 1–10 and normalizes to 0.0–1.0.
async fn ollama_confidence_check(
    model: &str,
    original_prompt: &str,
    response: &str,
) -> f32 {
    let system = "You are a confidence evaluator. Rate the quality and accuracy of the given response on a scale of 1-10. Respond with ONLY a single integer.";
    let prompt = format!(
        "Original question: {}\n\nResponse to evaluate: {}\n\nConfidence rating (1-10):",
        original_prompt, response
    );

    match ollama_generate(model, system, &prompt).await {
        Ok(rating_text) => {
            // Parse the first digit found
            rating_text
                .chars()
                .find(|c| c.is_ascii_digit())
                .and_then(|c| c.to_digit(10))
                .map(|d| (d as f32 / 10.0).clamp(0.1, 1.0))
                .unwrap_or(0.5)
        }
        Err(_) => 0.5, // Default confidence when check fails
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Core Thought Generation
// ─────────────────────────────────────────────────────────────────────────────

/// Generate thoughts based on the current context by querying Ollama.
async fn generate_thoughts_internal(
    context: &str,
    user_state: &UserState,
    min_score: f32,
) -> Result<Vec<(Thought, Option<String>, Option<String>, Option<String>)>, ImpForgeError> {
    let system_prompt = r#"You are an AI assistant that observes user activity and generates proactive, helpful thoughts. Your role is to notice things the user might miss and offer brief, actionable suggestions.

Respond ONLY with a JSON array. Each element has these fields:
- "content": a concise observation or suggestion (1-2 sentences)
- "title": a short title for the suggestion (5-8 words)
- "relevance": float 0-1, how relevant to the user's current task
- "urgency": float 0-1, how time-sensitive this is
- "novelty": float 0-1, how new or surprising
- "confidence": float 0-1, how confident you are
- "action_label": optional button text like "Open", "Apply", "Review" (or null)
- "action_route": optional app route like "/chat", "/ide", "/settings" (or null)

Generate 1-3 thoughts. Be genuinely helpful, not generic."#;

    let user_prompt = format!(
        "Current module: {}\nUser idle: {} seconds\nTyping: {}\nContext: {}",
        user_state.current_module,
        user_state.idle_seconds,
        user_state.is_typing,
        context,
    );

    // Determine which model to use — prefer small/fast models for background work
    let model = std::env::var("IMPFORGE_THOUGHTS_MODEL")
        .unwrap_or_else(|_| "dolphin3:8b".to_string());

    let raw = ollama_generate(&model, system_prompt, &user_prompt).await?;

    // Parse the JSON array from the response. Ollama sometimes wraps in markdown.
    let json_str = extract_json_array(&raw);
    let items: Vec<OllamaThoughtItem> = serde_json::from_str(&json_str).map_err(|e| {
        log::warn!("Failed to parse thought items: {e}. Raw: {raw}");
        ImpForgeError::internal("THOUGHT_PARSE_FAILED", format!("AI returned invalid JSON: {e}"))
    })?;

    let now = Utc::now().to_rfc3339();
    let mut results = Vec::new();

    for item in items {
        let score = calculate_score(item.relevance, item.urgency, item.novelty, item.confidence);
        if score < min_score {
            continue;
        }

        let thought = Thought {
            id: Uuid::new_v4().to_string(),
            content: item.content,
            trigger: TriggerType::UserActivity,
            relevance: item.relevance.clamp(0.0, 1.0),
            urgency: item.urgency.clamp(0.0, 1.0),
            novelty: item.novelty.clamp(0.0, 1.0),
            confidence: item.confidence.clamp(0.0, 1.0),
            score,
            created_at: now.clone(),
            surfaced: false,
            dismissed: false,
        };

        results.push((
            thought,
            item.title,
            item.action_label,
            item.action_route,
        ));
    }

    // Sort by score descending
    results.sort_by(|a, b| b.0.score.partial_cmp(&a.0.score).unwrap_or(std::cmp::Ordering::Equal));

    Ok(results)
}

/// Extract a JSON array from a string that might have markdown fences.
fn extract_json_array(raw: &str) -> String {
    let trimmed = raw.trim();

    // Try direct parse first
    if trimmed.starts_with('[') {
        return trimmed.to_string();
    }

    // Try to find JSON inside markdown code fences
    if let Some(start) = trimmed.find('[') {
        if let Some(end) = trimmed.rfind(']') {
            if end >= start {
                return trimmed[start..=end].to_string();
            }
        }
    }

    // Fallback: wrap as single-element array
    format!("[{}]", trimmed)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tauri Commands (10 total)
// ─────────────────────────────────────────────────────────────────────────────

/// Return current pending suggestions (max `max_suggestions` from config).
/// Only returns suggestions when the user is interruptible (not typing, idle enough).
#[tauri::command]
pub async fn thoughts_get_suggestions(
    engine: tauri::State<'_, InnerThoughtsEngine>,
) -> AppResult<Vec<Suggestion>> {
    let config = engine.config.read().clone();
    if !config.enabled {
        return Ok(Vec::new());
    }

    let user_state = engine.user_state.read().clone();
    if !user_state.interruptible || user_state.is_typing {
        return Ok(Vec::new());
    }

    let suggestions = engine.suggestions.read().clone();
    let max = config.max_suggestions as usize;
    Ok(suggestions.into_iter().take(max).collect())
}

/// User dismissed a suggestion — record negative feedback.
#[tauri::command]
pub async fn thoughts_dismiss(
    engine: tauri::State<'_, InnerThoughtsEngine>,
    suggestion_id: String,
) -> AppResult<()> {
    let thought_id = {
        let mut suggestions = engine.suggestions.write();
        let pos = suggestions.iter().position(|s| s.id == suggestion_id);
        if let Some(idx) = pos {
            let removed = suggestions.remove(idx);
            Some(removed.thought_id)
        } else {
            None
        }
    };

    // Mark the underlying thought as dismissed
    if let Some(tid) = thought_id {
        let mut thoughts = engine.thoughts.write();
        if let Some(thought) = thoughts.iter_mut().find(|t| t.id == tid) {
            thought.dismissed = true;
            // Persist updated state (fire-and-forget)
            let _ = persist_thought(thought);
        }
    }

    log::info!("Suggestion dismissed: {suggestion_id}");
    Ok(())
}

/// User accepted a suggestion — record positive feedback.
#[tauri::command]
pub async fn thoughts_accept(
    engine: tauri::State<'_, InnerThoughtsEngine>,
    suggestion_id: String,
) -> AppResult<()> {
    let thought_id = {
        let mut suggestions = engine.suggestions.write();
        let pos = suggestions.iter().position(|s| s.id == suggestion_id);
        if let Some(idx) = pos {
            let removed = suggestions.remove(idx);
            Some(removed.thought_id)
        } else {
            None
        }
    };

    // Mark the underlying thought as surfaced (accepted)
    if let Some(tid) = thought_id {
        let mut thoughts = engine.thoughts.write();
        if let Some(thought) = thoughts.iter_mut().find(|t| t.id == tid) {
            thought.surfaced = true;
            let _ = persist_thought(thought);
        }
    }

    log::info!("Suggestion accepted: {suggestion_id}");
    Ok(())
}

/// Generate thoughts based on current context.
/// Uses Ollama to analyze the context and produce scored thoughts.
#[tauri::command]
pub async fn thoughts_generate(
    engine: tauri::State<'_, InnerThoughtsEngine>,
    context: String,
) -> AppResult<Vec<Thought>> {
    let config = engine.config.read().clone();
    if !config.enabled {
        return Ok(Vec::new());
    }

    let user_state = engine.user_state.read().clone();
    let min_score = config.min_score_to_surface;
    let max_suggestions = config.max_suggestions as usize;

    let generated = generate_thoughts_internal(&context, &user_state, min_score).await?;

    let mut new_thoughts = Vec::new();
    let mut new_suggestions = Vec::new();
    let now = Utc::now().to_rfc3339();

    for (thought, title, action_label, action_route) in &generated {
        new_thoughts.push(thought.clone());

        // Create suggestion from thought
        let suggestion = Suggestion {
            id: Uuid::new_v4().to_string(),
            thought_id: thought.id.clone(),
            title: title.clone().unwrap_or_else(|| {
                thought.content.chars().take(50).collect::<String>()
            }),
            description: thought.content.clone(),
            action_label: action_label.clone(),
            action_route: action_route.clone(),
            priority: score_to_priority(thought.score),
            created_at: now.clone(),
        };
        new_suggestions.push(suggestion);

        // Persist each thought to disk
        let _ = persist_thought(thought);
    }

    // Add to engine state (capped at max_suggestions)
    {
        let mut thoughts = engine.thoughts.write();
        thoughts.extend(new_thoughts.clone());
        // Keep last 100 thoughts in memory
        if thoughts.len() > 100 {
            let drain_count = thoughts.len() - 100;
            thoughts.drain(..drain_count);
        }
    }
    {
        let mut suggestions = engine.suggestions.write();
        suggestions.extend(new_suggestions);
        // Cap at max_suggestions
        suggestions.sort_by(|a, b| b.priority.cmp(&a.priority));
        suggestions.truncate(max_suggestions);
    }

    Ok(new_thoughts)
}

/// Get the current thoughts configuration.
#[tauri::command]
pub async fn thoughts_get_config(
    engine: tauri::State<'_, InnerThoughtsEngine>,
) -> AppResult<ThoughtsConfig> {
    Ok(engine.config.read().clone())
}

/// Save a new thoughts configuration (persisted to disk).
#[tauri::command]
pub async fn thoughts_save_config(
    engine: tauri::State<'_, InnerThoughtsEngine>,
    config: ThoughtsConfig,
) -> AppResult<()> {
    save_config_to_disk(&config)?;
    *engine.config.write() = config;
    log::info!("Inner Thoughts config saved");
    Ok(())
}

/// Update user state from the frontend (module change, typing state).
/// Called by the frontend on navigation and typing events.
#[tauri::command]
pub async fn thoughts_update_user_state(
    engine: tauri::State<'_, InnerThoughtsEngine>,
    module: String,
    is_typing: bool,
) -> AppResult<()> {
    let config = engine.config.read().clone();
    let now = Utc::now();
    let mut state = engine.user_state.write();

    // Calculate idle time from last action
    let last_action = chrono::DateTime::parse_from_rfc3339(&state.last_action_at)
        .map(|dt| dt.with_timezone(&Utc))
        .unwrap_or(now);
    let idle = (now - last_action).num_seconds().max(0) as u64;

    if is_typing || state.current_module != module {
        // User just did something — reset idle
        state.last_action_at = now.to_rfc3339();
        state.idle_seconds = 0;
        state.interruptible = false;
    } else {
        state.idle_seconds = idle;
        state.interruptible = idle >= config.idle_threshold_seconds as u64;
    }

    state.current_module = module;
    state.is_typing = is_typing;

    Ok(())
}

/// Get thought history (all past thoughts, most recent first).
#[tauri::command]
pub async fn thoughts_get_history(
    limit: u32,
) -> AppResult<Vec<Thought>> {
    let effective_limit = if limit == 0 { 50 } else { limit.min(500) };
    load_thought_history(effective_limit)
}

/// Cascade inference: try local model first, escalate to cloud if confidence < threshold.
///
/// 1. Send prompt to Ollama (local, free, private).
/// 2. Ask Ollama to self-rate confidence (1–10).
/// 3. If confidence < `max_confidence` (default 0.8) → retry via OpenRouter free-tier.
/// 4. Return the best response with metadata.
#[tauri::command]
pub async fn cascade_infer(
    engine: tauri::State<'_, InnerThoughtsEngine>,
    prompt: String,
    max_confidence: Option<f32>,
) -> AppResult<CascadeResult> {
    let threshold = max_confidence.unwrap_or(0.8).clamp(0.1, 1.0);
    let start = std::time::Instant::now();

    // Step 1: Try local Ollama
    let local_model = std::env::var("IMPFORGE_CASCADE_MODEL")
        .unwrap_or_else(|_| "dolphin3:8b".to_string());

    let local_result = ollama_generate(
        &local_model,
        "You are a helpful AI assistant. Provide accurate, detailed answers.",
        &prompt,
    )
    .await;

    match local_result {
        Ok(response) if !response.trim().is_empty() => {
            // Step 2: Confidence check
            let confidence = ollama_confidence_check(&local_model, &prompt, &response).await;
            let latency_ms = start.elapsed().as_millis() as u64;

            if confidence >= threshold {
                // Local model is confident enough — use it
                engine.record_inference(true, confidence, latency_ms);
                return Ok(CascadeResult {
                    response,
                    model_used: local_model,
                    confidence,
                    escalated: false,
                    latency_ms,
                });
            }

            log::info!(
                "Cascade: local confidence {confidence:.2} < threshold {threshold:.2}, escalating to cloud"
            );

            // Step 3: Escalate to OpenRouter free-tier
            match escalate_to_cloud(&prompt).await {
                Ok(cloud_response) => {
                    let latency_ms = start.elapsed().as_millis() as u64;
                    engine.record_inference(false, confidence, latency_ms);
                    Ok(CascadeResult {
                        response: cloud_response,
                        model_used: "openrouter/free-tier".to_string(),
                        confidence: 0.9, // Cloud models generally more capable
                        escalated: true,
                        latency_ms,
                    })
                }
                Err(_) => {
                    // Cloud failed too — return local result anyway
                    engine.record_inference(true, confidence, latency_ms);
                    Ok(CascadeResult {
                        response,
                        model_used: local_model,
                        confidence,
                        escalated: false,
                        latency_ms,
                    })
                }
            }
        }
        Ok(_) | Err(_) => {
            // Local model unavailable or empty response — try cloud directly
            match escalate_to_cloud(&prompt).await {
                Ok(cloud_response) => {
                    let latency_ms = start.elapsed().as_millis() as u64;
                    engine.record_inference(false, 0.9, latency_ms);
                    Ok(CascadeResult {
                        response: cloud_response,
                        model_used: "openrouter/free-tier".to_string(),
                        confidence: 0.9,
                        escalated: true,
                        latency_ms,
                    })
                }
                Err(e) => {
                    Err(ImpForgeError::service(
                        "CASCADE_ALL_FAILED",
                        "Both local and cloud inference failed",
                    )
                    .with_details(e.to_string())
                    .with_suggestion("Check that Ollama is running, or configure an OpenRouter API key in Settings."))
                }
            }
        }
    }
}

/// Escalate a prompt to OpenRouter free-tier model.
async fn escalate_to_cloud(prompt: &str) -> Result<String, ImpForgeError> {
    let api_key = std::env::var("OPENROUTER_API_KEY").map_err(|_| {
        ImpForgeError::config(
            "MISSING_OPENROUTER_KEY",
            "No OpenRouter API key configured for cascade escalation",
        )
        .with_suggestion("Add your OpenRouter API key in Settings > API Keys.")
    })?;

    if api_key.is_empty() {
        return Err(ImpForgeError::config(
            "EMPTY_OPENROUTER_KEY",
            "OpenRouter API key is empty",
        ));
    }

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .build()
        .map_err(|e| ImpForgeError::internal("HTTP_CLIENT_ERROR", e.to_string()))?;

    let body = serde_json::json!({
        "model": "meta-llama/llama-4-scout:free",
        "messages": [
            { "role": "system", "content": "You are a helpful AI assistant. Provide accurate, detailed answers." },
            { "role": "user", "content": prompt },
        ],
        "max_tokens": 1024,
    });

    let resp = client
        .post("https://openrouter.ai/api/v1/chat/completions")
        .header("Authorization", format!("Bearer {api_key}"))
        .header("HTTP-Referer", "https://impforge.dev")
        .header("X-Title", "ImpForge Cascade Inference")
        .json(&body)
        .send()
        .await
        .map_err(|e| {
            ImpForgeError::service("OPENROUTER_REQUEST_FAILED", format!("OpenRouter request failed: {e}"))
        })?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body_text = resp.text().await.unwrap_or_default();
        return Err(ImpForgeError::service(
            "OPENROUTER_HTTP_ERROR",
            format!("OpenRouter returned HTTP {status}"),
        )
        .with_details(body_text));
    }

    let parsed: serde_json::Value = resp.json().await.map_err(|e| {
        ImpForgeError::service("OPENROUTER_PARSE_ERROR", format!("Failed to parse OpenRouter response: {e}"))
    })?;

    let content = parsed
        .pointer("/choices/0/message/content")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    if content.is_empty() {
        return Err(ImpForgeError::service(
            "OPENROUTER_EMPTY_RESPONSE",
            "OpenRouter returned an empty response",
        ));
    }

    Ok(content)
}

/// Get cascade inference statistics.
#[tauri::command]
pub async fn cascade_get_stats(
    engine: tauri::State<'_, InnerThoughtsEngine>,
) -> AppResult<CascadeStats> {
    Ok(engine.get_stats())
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_calculate_score() {
        // Perfect scores
        let score = calculate_score(1.0, 1.0, 1.0, 1.0);
        assert!((score - 1.0).abs() < f32::EPSILON);

        // Zero scores
        let score = calculate_score(0.0, 0.0, 0.0, 0.0);
        assert!((score - 0.0).abs() < f32::EPSILON);

        // Weighted: relevance=1, rest=0 → 0.3
        let score = calculate_score(1.0, 0.0, 0.0, 0.0);
        assert!((score - 0.3).abs() < 0.001);

        // urgency=1, rest=0 → 0.3
        let score = calculate_score(0.0, 1.0, 0.0, 0.0);
        assert!((score - 0.3).abs() < 0.001);

        // novelty=1, rest=0 → 0.2
        let score = calculate_score(0.0, 0.0, 1.0, 0.0);
        assert!((score - 0.2).abs() < 0.001);

        // confidence=1, rest=0 → 0.2
        let score = calculate_score(0.0, 0.0, 0.0, 1.0);
        assert!((score - 0.2).abs() < 0.001);
    }

    #[test]
    fn test_calculate_score_clamps() {
        // Values outside 0-1 should be clamped
        let score = calculate_score(2.0, -1.0, 1.5, 0.5);
        // Clamped: 1.0*0.3 + 0.0*0.3 + 1.0*0.2 + 0.5*0.2 = 0.3 + 0 + 0.2 + 0.1 = 0.6
        assert!((score - 0.6).abs() < 0.001);
    }

    #[test]
    fn test_score_to_priority() {
        assert_eq!(score_to_priority(0.95), SuggestionPriority::Critical);
        assert_eq!(score_to_priority(0.9), SuggestionPriority::Critical);
        assert_eq!(score_to_priority(0.8), SuggestionPriority::High);
        assert_eq!(score_to_priority(0.75), SuggestionPriority::High);
        assert_eq!(score_to_priority(0.65), SuggestionPriority::Medium);
        assert_eq!(score_to_priority(0.6), SuggestionPriority::Medium);
        assert_eq!(score_to_priority(0.5), SuggestionPriority::Low);
        assert_eq!(score_to_priority(0.0), SuggestionPriority::Low);
    }

    #[test]
    fn test_extract_json_array_direct() {
        let input = r#"[{"content":"test","relevance":0.8}]"#;
        let result = extract_json_array(input);
        assert!(result.starts_with('['));
        assert!(result.ends_with(']'));
    }

    #[test]
    fn test_extract_json_array_markdown_fenced() {
        let input = "```json\n[{\"content\":\"test\"}]\n```";
        let result = extract_json_array(input);
        assert!(result.starts_with('['));
        assert!(result.ends_with(']'));
    }

    #[test]
    fn test_extract_json_array_with_prefix_text() {
        let input = "Here are the thoughts:\n[{\"content\":\"idea\"}]";
        let result = extract_json_array(input);
        assert!(result.starts_with('['));
        assert!(result.ends_with(']'));
    }

    #[test]
    fn test_thoughts_config_default() {
        let config = ThoughtsConfig::default();
        assert!(config.enabled);
        assert!((config.min_score_to_surface - 0.6).abs() < f32::EPSILON);
        assert_eq!(config.max_suggestions, 3);
        assert_eq!(config.check_interval_seconds, 30);
        assert_eq!(config.idle_threshold_seconds, 5);
    }

    #[test]
    fn test_user_state_default() {
        let state = UserState::default();
        assert_eq!(state.current_module, "home");
        assert!(!state.is_typing);
        assert!(state.interruptible);
        assert_eq!(state.idle_seconds, 0);
    }

    #[test]
    fn test_thought_serialization() {
        let thought = Thought {
            id: "test-id".to_string(),
            content: "You should commit your changes".to_string(),
            trigger: TriggerType::PatternDetected,
            relevance: 0.8,
            urgency: 0.6,
            novelty: 0.5,
            confidence: 0.9,
            score: calculate_score(0.8, 0.6, 0.5, 0.9),
            created_at: "2026-03-18T10:00:00Z".to_string(),
            surfaced: false,
            dismissed: false,
        };

        let json = serde_json::to_string(&thought);
        assert!(json.is_ok());
        let json_str = json.expect("serialization should succeed");
        assert!(json_str.contains("pattern_detected"));
        assert!(json_str.contains("test-id"));
    }

    #[test]
    fn test_suggestion_serialization() {
        let suggestion = Suggestion {
            id: "sug-1".to_string(),
            thought_id: "thought-1".to_string(),
            title: "Consider running tests".to_string(),
            description: "You changed 3 files but haven't run tests yet.".to_string(),
            action_label: Some("Run Tests".to_string()),
            action_route: Some("/ide".to_string()),
            priority: SuggestionPriority::High,
            created_at: "2026-03-18T10:00:00Z".to_string(),
        };

        let json = serde_json::to_string(&suggestion);
        assert!(json.is_ok());
        let json_str = json.expect("serialization should succeed");
        assert!(json_str.contains("high"));
        assert!(json_str.contains("Run Tests"));
    }

    #[test]
    fn test_cascade_result_serialization() {
        let result = CascadeResult {
            response: "Hello, world!".to_string(),
            model_used: "dolphin3:8b".to_string(),
            confidence: 0.85,
            escalated: false,
            latency_ms: 1234,
        };

        let json = serde_json::to_string(&result).expect("should serialize");
        assert!(json.contains("dolphin3:8b"));
        assert!(json.contains("1234"));
    }

    #[test]
    fn test_cascade_stats_default() {
        let engine = InnerThoughtsEngine::new();
        let stats = engine.get_stats();
        assert_eq!(stats.total_inferences, 0);
        assert_eq!(stats.local_inferences, 0);
        assert_eq!(stats.cloud_inferences, 0);
        assert!((stats.avg_local_confidence - 0.0).abs() < f32::EPSILON);
    }

    #[test]
    fn test_record_inference_local() {
        let engine = InnerThoughtsEngine::new();
        engine.record_inference(true, 0.85, 500);
        engine.record_inference(true, 0.75, 300);

        let stats = engine.get_stats();
        assert_eq!(stats.total_inferences, 2);
        assert_eq!(stats.local_inferences, 2);
        assert_eq!(stats.cloud_inferences, 0);
        assert!((stats.avg_local_confidence - 0.8).abs() < 0.01);
    }

    #[test]
    fn test_record_inference_cloud() {
        let engine = InnerThoughtsEngine::new();
        engine.record_inference(false, 0.9, 1000);

        let stats = engine.get_stats();
        assert_eq!(stats.total_inferences, 1);
        assert_eq!(stats.local_inferences, 0);
        assert_eq!(stats.cloud_inferences, 1);
    }

    #[test]
    fn test_trigger_type_serialization() {
        let triggers = vec![
            TriggerType::UserActivity,
            TriggerType::ContextChange,
            TriggerType::TimeBasedReminder,
            TriggerType::PatternDetected,
            TriggerType::ErrorDetected,
            TriggerType::GoalProgress,
        ];

        for trigger in &triggers {
            let json = serde_json::to_string(trigger).expect("should serialize");
            let parsed: TriggerType = serde_json::from_str(&json).expect("should deserialize");
            assert_eq!(&parsed, trigger);
        }
    }

    #[test]
    fn test_suggestion_priority_ordering() {
        assert!(SuggestionPriority::Critical > SuggestionPriority::High);
        assert!(SuggestionPriority::High > SuggestionPriority::Medium);
        assert!(SuggestionPriority::Medium > SuggestionPriority::Low);
    }
}
